- name: Install base packages
  hosts: homelab
  become: true

  tasks:
    - name: Install basic tools
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - git
          - ca-certificates
          - gnupg
          - lsb-release
          - mc
          - htop
          - nano
        state: present
        update_cache: true
